name: Publish Retype powered website to GitHub Pages
on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  publish:
    name: Publish to retype branch

    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v6

      - name: Generate llms.txt
        uses: zakaria-chahboun/retype_llms@v3.0.1

      - uses: retypeapp/action-build@latest
        with:
          key: ${{ secrets.RETYPE_PASSWORD }}

      - uses: retypeapp/action-github-pages@latest
        with:
          update-branch: true
